"""Удалено  поле name в модель User

Revision ID: c7bedc590dda
Revises: cea60b79140b
Create Date: 2024-06-22 10:07:56.827829

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c7bedc590dda"
down_revision = "cea60b79140b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("name")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("name", sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
