"""Добавлено поле name в модель User

Revision ID: cea60b79140b
Revises: 
Create Date: 2024-06-22 09:45:29.556799

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cea60b79140b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("name", sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("name")

    # ### end Alembic commands ###
